// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAF30w9WSn_0ts0j2GBApYESH0p0Kgu8MM',
    appId: '1:873002121178:web:2d8d01d577354f896972e3',
    messagingSenderId: '873002121178',
    projectId: 'dam-ai',
    authDomain: 'dam-ai.firebaseapp.com',
    storageBucket: 'dam-ai.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAS_h-htEVFh6fGwLYgVJ27M8crKkCH_kc',
    appId: '1:873002121178:android:2eb3043ca32bac066972e3',
    messagingSenderId: '873002121178',
    projectId: 'dam-ai',
    storageBucket: 'dam-ai.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9VQcEMwlFLwxBbwAtKZF7-xv6HrxlZ_Y',
    appId: '1:873002121178:ios:45e02a84711bda496972e3',
    messagingSenderId: '873002121178',
    projectId: 'dam-ai',
    storageBucket: 'dam-ai.appspot.com',
    iosBundleId: 'com.example.damAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9VQcEMwlFLwxBbwAtKZF7-xv6HrxlZ_Y',
    appId: '1:873002121178:ios:45e02a84711bda496972e3',
    messagingSenderId: '873002121178',
    projectId: 'dam-ai',
    storageBucket: 'dam-ai.appspot.com',
    iosBundleId: 'com.example.damAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAF30w9WSn_0ts0j2GBApYESH0p0Kgu8MM',
    appId: '1:873002121178:web:b00286ae46f577bf6972e3',
    messagingSenderId: '873002121178',
    projectId: 'dam-ai',
    authDomain: 'dam-ai.firebaseapp.com',
    storageBucket: 'dam-ai.appspot.com',
  );
}
